# Generated by Django 4.1.4 on 2022-12-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatbot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='user',
            new_name='owner',
        ),
    ]
