# Generated by Django 4.1.5 on 2023-01-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_intent_rename_content_chatbot_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intent',
            name='name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
