# Generated by Django 4.1.5 on 2023-01-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_intent_description_intent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='chatbot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_intents', to='chatbot.chatbot'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='chatbot.intent'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='chatbot.intent'),
        ),
    ]
