# Generated by Django 4.1.5 on 2023-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_slot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='description',
            field=models.TextField(blank=True, default='no description given', null=True),
        ),
    ]
