# Generated by Django 4.1.5 on 2023-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_alter_chatbot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='description',
            field=models.TextField(default='no description given'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='description',
            field=models.TextField(default='no description given'),
        ),
    ]
