# Generated by Django 4.1.5 on 2023-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_chatbot_description_alter_intent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.TextField(default='fag'),
            preserve_default=False,
        ),
    ]
